#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
54 - Publication-level figure deck (PowerPoint)
==============================================
Lays every atlas figure onto a 16:9 widescreen slide using one fixed geometry, so
that across the whole deck the title band, the figure box and the caption band sit
at exactly the same coordinates on every slide.

Layout guarantees (this is the point of the script):
  * The three zones -- title band / figure box / caption band -- are disjoint
    rectangles. Nothing can overlap, because nothing is free-positioned.
  * Every figure is scaled to FIT its box with its aspect ratio preserved, then
    centred both ways, so margins are even on all four sides.
  * Figures far taller than the box (e.g. a 1636x8431 direction map) are sliced
    into equal vertical panels laid side by side, so they fill the box legibly
    instead of collapsing into an unreadable sliver.
  * Caption text is auto-shrunk to the caption band; it never spills into the
    figure box or off the slide.

Inputs : 08_figures/**/*.png  (already generated by src/26..53)
         09_tables/*.tsv, 06_genetic_causality/*.tsv  (for the live cover numbers)
Output : 08_figures/Human_Plasma_Immune_Atlas_Figures.pptx
         (plus a cardiovascular-only deck, Cardiovascular_Novelty_Figures.pptx)

Run:  python src/54_build_publication_ppt.py
"""
import os
import textwrap
import pandas as pd
from PIL import Image

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR

ROOT = r"I:\Plasma immune atalas"
FIG  = os.path.join(ROOT, "08_figures")
GC   = os.path.join(ROOT, "06_genetic_causality")
TMP  = os.path.join(FIG, "_ppt_cache")
os.makedirs(TMP, exist_ok=True)

# ---------------------------------------------------------------- geometry
SW, SH = 13.3333, 7.5                 # 16:9 widescreen, inches
M      = 0.42                         # outer margin

BAND_Y      = 0.30                    # title band top
BAND_H      = 0.86                    # title band height  (title + subtitle)
FIG_Y       = BAND_Y + BAND_H + 0.14  # figure box top      = 1.30
CAP_H       = 0.92                    # caption band height
FOOT_H      = 0.30
CAP_Y       = SH - FOOT_H - CAP_H - 0.10          # = 6.18
FIG_H       = CAP_Y - FIG_Y - 0.16                # = 4.72
FIG_X, FIG_W = M, SW - 2 * M                      # = 0.42, 12.49
FOOT_Y      = SH - FOOT_H - 0.06

INK   = RGBColor(0x1A, 0x1A, 0x1A)
ACC   = RGBColor(0x7D, 0x11, 0x28)     # deep carmine, matches the figures
ACC2  = RGBColor(0xC0, 0x39, 0x2B)
GREY  = RGBColor(0x6B, 0x6B, 0x6B)
LIGHT = RGBColor(0xF4, 0xF4, 0xF6)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
FONT  = "Calibri"


def txbox(slide, x, y, w, h, text, size=14, bold=False, color=INK,
          align=PP_ALIGN.LEFT, anchor=MSO_ANCHOR.TOP, italic=False, spacing=1.0):
    tb = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = tb.text_frame
    tf.word_wrap = True
    tf.margin_left = tf.margin_right = tf.margin_top = tf.margin_bottom = 0
    tf.vertical_anchor = anchor
    p = tf.paragraphs[0]
    p.alignment = align
    p.line_spacing = spacing
    r = p.add_run(); r.text = text
    f = r.font
    f.name, f.size, f.bold, f.italic, f.color.rgb = FONT, Pt(size), bold, italic, color
    return tb


def rect(slide, x, y, w, h, fill, line=None):
    from pptx.enum.shapes import MSO_SHAPE
    s = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(x), Inches(y),
                               Inches(w), Inches(h))
    s.fill.solid(); s.fill.fore_color.rgb = fill
    if line is None:
        s.line.fill.background()
    else:
        s.line.color.rgb = line
    s.shadow.inherit = False
    return s


# ---------------------------------------------------------------- image fitting
def _row_ink(im):
    """Per-row 'has ink' mask, subsampled across the width for speed."""
    px = im.convert("L").load()
    w, h = im.size
    step = max(1, w // 300)
    return [any(px[x, y] < 205 for x in range(0, w, step)) for y in range(h)]


def strip_baked_title(path, strip=True):
    """Most archival figures carry their own 'Figure N | ...' banner, which would
    duplicate the slide header. Remove it when the top of the image is one or two
    thin text lines separated from the plot body by a clear white gap.

    Then trim the surrounding white border, so every figure fills its box with even
    margins instead of inheriting whatever padding matplotlib happened to leave.

    strip=False is used for the figures built by this script: they carry no banner, but
    they do carry a left-aligned 'A · ...' panel title in exactly the place a banner
    would sit, and losing that would silently delete a panel label.
    """
    im = Image.open(path).convert("RGB")
    w, h = im.size
    ink = _row_ink(im)
    if not any(ink):
        return path

    # ---- 1. drop a single leading title line, and only when it is unambiguous.
    # Exactly one line is removed: an earlier two-line version silently ate the first
    # bar of ranked bar charts, because a bar is also "a thin band then a gap".
    # The discriminator is that a title is followed by a gap AT LEAST as tall as the
    # text itself, whereas bars in a ranked chart sit closer together than they are thick.
    y0 = ink.index(True)
    if strip and y0 <= h * 0.05:
        y = y0
        while y < h and ink[y]:
            y += 1
        band = y - y0
        gap0 = y
        while y < h and not ink[y]:
            y += 1
        gap = y - gap0
        if 3 <= band <= h * 0.075 and gap >= band and gap0 + gap // 2 < h * 0.22:
            im = im.crop((0, gap0 + gap // 2, w, h))

    # ---- 2. trim the white frame so margins on the slide are even
    g = im.convert("L")
    bbox = g.point(lambda v: 255 if v < 246 else 0).getbbox()
    if bbox:
        pad = max(4, int(min(im.size) * 0.008))
        im = im.crop((max(0, bbox[0] - pad), max(0, bbox[1] - pad),
                      min(im.size[0], bbox[2] + pad), min(im.size[1], bbox[3] + pad)))

    p = os.path.join(TMP, "trim_" + os.path.basename(path))
    im.save(p)
    return p


def prepared(path, box_ar):
    """Return a path whose aspect ratio is usable inside a box of ratio box_ar.

    A figure much taller than the box (a long ranked bar chart) is cut into k
    equal-height panels laid left-to-right with a thin gutter. k is chosen so the
    reassembled image lands as close as possible to the box ratio, which is what
    makes those figures readable on a 16:9 slide instead of a 2-cm-wide strip.

    The threshold is deliberately severe. An earlier, looser one (anything narrower
    than 0.42 of the box ratio) sliced a SQUARE scatter plot down the middle and laid
    the two halves side by side, which destroys the figure rather than fitting it.
    Only a figure at least twice as tall as it is wide can be cut safely, because only
    a stacked/ranked chart has that shape; everything squarer goes to the TALL slide
    layout instead, where it keeps its full height next to a caption column.
    """
    im = Image.open(path).convert("RGB")
    w, h = im.size
    ar = w / h
    if ar >= 0.5:
        return path, ar
    k = max(2, min(4, round((box_ar / ar) ** 0.5)))
    band = h // k
    gut = max(12, w // 90)
    out = Image.new("RGB", (w * k + gut * (k - 1), band), "white")
    for i in range(k):
        out.paste(im.crop((0, i * band, w, (i + 1) * band)), (i * (w + gut), 0))
    p = os.path.join(TMP, f"split{k}_" + os.path.basename(path))
    out.save(p)
    return p, out.size[0] / out.size[1]


def place(slide, path, ar, x, y, w, h):
    """Fit-and-centre inside (x,y,w,h). Never crops, never overflows."""
    box_ar = w / h
    if ar >= box_ar:                              # width-limited
        dw, dh = w, w / ar
    else:                                         # height-limited
        dh, dw = h, h * ar
    slide.shapes.add_picture(path, Inches(x + (w - dw) / 2), Inches(y + (h - dh) / 2),
                             Inches(dw), Inches(dh))


# ---------------------------------------------------------------- slide makers
def new_deck():
    prs = Presentation()
    prs.slide_width, prs.slide_height = Inches(SW), Inches(SH)
    return prs


def blank(prs):
    return prs.slides.add_slide(prs.slide_layouts[6])


def footer(slide, n, tag):
    txbox(slide, M, FOOT_Y, SW - 2 * M - 0.8, FOOT_H,
          f"Human Plasma Immune Atlas   ·   {tag}", size=8.5, color=GREY,
          anchor=MSO_ANCHOR.MIDDLE)
    txbox(slide, SW - M - 0.8, FOOT_Y, 0.8, FOOT_H, str(n), size=8.5,
          color=GREY, align=PP_ALIGN.RIGHT, anchor=MSO_ANCHOR.MIDDLE)


def cap_size(text, area):
    """Point size that keeps the caption inside its band. area is in square inches."""
    for sz in (11.5, 11, 10.5, 10, 9.5, 9, 8.5, 8):
        # ~ characters that fit per square inch at this size, measured empirically
        if len(text) <= area * (150 * (10.0 / sz) ** 2):
            return sz
    return 7.5


def fig_slide(prs, n, tag, label, title, path, caption, subtitle=None):
    """Two layout modes, chosen from the figure's own aspect ratio, so that no slide
    is ever half empty:
      WIDE  (landscape figure)  -> figure spans the full width, caption underneath.
      TALL  (squarish or tall)  -> figure takes the full slide height on the left and
                                   the caption moves into a right-hand column.
    In both modes the zones are disjoint rectangles, so overlap is impossible."""
    s = blank(prs)
    rect(s, 0, 0, SW, 0.16, ACC)                              # top rule
    rect(s, M, BAND_Y + 0.04, 0.075, BAND_H - 0.08, ACC2)     # accent tick
    txbox(s, M + 0.20, BAND_Y, SW - 2 * M - 0.20, 0.40,
          f"{label}  |  {title}", size=19, bold=True, color=INK,
          anchor=MSO_ANCHOR.MIDDLE)
    if subtitle:
        txbox(s, M + 0.20, BAND_Y + 0.44, SW - 2 * M - 0.20, 0.38,
              subtitle, size=11.5, color=GREY, anchor=MSO_ANCHOR.MIDDLE)

    # slice very tall figures first, so the mode is chosen from what will actually
    # be drawn rather than from the raw file
    deck_native = os.path.basename(os.path.dirname(path)) == "deck"
    src, ar = prepared(strip_baked_title(path, strip=not deck_native), FIG_W / FIG_H)
    tall_h = FOOT_Y - 0.14 - FIG_Y                       # full remaining height

    if ar >= 1.85:                                       # ---- WIDE
        place(s, src, ar, FIG_X, FIG_Y, FIG_W, FIG_H)
        rect(s, M, CAP_Y, SW - 2 * M, 0.022, RGBColor(0xDD, 0xDD, 0xE0))
        cx, cy, cw, ch = M, CAP_Y + 0.10, SW - 2 * M, CAP_H - 0.10
    else:                                                # ---- TALL
        # split the width between figure and caption according to what the figure
        # actually needs at full height, so a near-square figure does not sit in a
        # wide box surrounded by dead space while the caption is squeezed.
        avail = SW - 2 * M - 0.34
        fw = min(avail - 2.95, max(avail - 4.65, tall_h * ar))
        cw = avail - fw
        place(s, src, ar, FIG_X, FIG_Y, fw, tall_h)
        cx = FIG_X + fw + 0.34
        cy, ch = FIG_Y, tall_h
        rect(s, cx, cy, 0.022, ch, RGBColor(0xDD, 0xDD, 0xE0))
        cx += 0.20; cw -= 0.20

    txbox(s, cx, cy, cw, ch, caption, size=cap_size(caption, cw * ch),
          color=RGBColor(0x33, 0x33, 0x33), spacing=1.10)
    footer(s, n, tag)
    return s


def section_slide(prs, n, kicker, title, blurb, bullets=()):
    s = blank(prs)
    rect(s, 0, 0, SW, SH, ACC)
    rect(s, 0, 0, 0.34, SH, ACC2)
    txbox(s, 1.15, 2.05, SW - 2.3, 0.45, kicker.upper(), size=13, bold=True,
          color=RGBColor(0xF2, 0xB8, 0xB8))
    txbox(s, 1.15, 2.52, SW - 2.3, 1.05, title, size=34, bold=True, color=WHITE)
    txbox(s, 1.15, 3.72, SW - 3.0, 0.9, blurb, size=13.5,
          color=RGBColor(0xF0, 0xE0, 0xE2), spacing=1.15)
    y = 4.72
    for b in bullets:
        txbox(s, 1.30, y, 0.3, 0.32, "—", size=13, bold=True, color=ACC2 if False else
              RGBColor(0xF2, 0xB8, 0xB8))
        txbox(s, 1.62, y, SW - 3.2, 0.32, b, size=12.5, color=WHITE)
        y += 0.42
    txbox(s, 1.15, FOOT_Y, SW - 2.3, FOOT_H, "Human Plasma Immune Atlas",
          size=9, color=RGBColor(0xE0, 0xB0, 0xB4), anchor=MSO_ANCHOR.MIDDLE)
    return s


def stat_grid(slide, y, items, h=1.05):
    """Evenly spaced stat cards: gutters computed from the count, so any number
    of cards stays flush with the same left/right margins as everything else."""
    k = len(items)
    gut = 0.22
    w = (SW - 2 * M - gut * (k - 1)) / k
    for i, (big, small) in enumerate(items):
        x = M + i * (w + gut)
        rect(slide, x, y, w, h, LIGHT)
        rect(slide, x, y, w, 0.055, ACC2)
        txbox(slide, x + 0.12, y + 0.16, w - 0.24, 0.46, big, size=23, bold=True,
              color=ACC, align=PP_ALIGN.CENTER)
        txbox(slide, x + 0.10, y + 0.62, w - 0.20, 0.38, small, size=9.5,
              color=GREY, align=PP_ALIGN.CENTER)


# ---------------------------------------------------------------- live numbers
print("[54] reading result tables for the cover statistics ...")
NOV = pd.read_csv(os.path.join(GC, "novelty_engine_ranked_ALL.tsv"), sep="\t")
CV = NOV[NOV["disease_system"] == "Cardiovascular"]
N_PAIRS = len(NOV)
N_PROTS = NOV["gene_symbol"].nunique()
N_DIS = NOV["disease"].nunique()
N_COLOC = int((NOV["PP_H4"] >= 0.8).sum())
N_REPL = int(NOV["two_population_validated"].sum())
CV_N, CV_G, CV_D = len(CV), CV["gene_symbol"].nunique(), CV["disease"].nunique()
CV_COLOC = int((CV["PP_H4"] >= 0.8).sum())
CV_REPL = int(CV["two_population_validated"].sum())
CV_NOVEL = int(CV["category_label"].isin(
    ["NOVEL colocalized", "NOVEL protein-confirmed"]).sum())
CV_KNOWN = int((CV["category_label"] == "recovered known axis").sum())
CV_DRUG = int((CV["druggability"] > 0).sum())
print(f"  phenome: {N_PAIRS:,} causal pairs | cardiovascular: {CV_N}")


# ============================================ slide-native whole-phenome figures
# Two separate problems are solved here.
#
# (1) Resolution. The archival direction map is 1636 x 8431 px: on a 33-cm slide every
#     label would be under half a millimetre tall. A deck needs the same statement at
#     slide resolution, so it is recomputed rather than shrunk.
# (2) Scope. Several archival figures were drawn in an earlier era of the project, when
#     the scan covered 13 or 28 curated endpoints. The deck must speak for the WHOLE
#     FinnGen R12 phenome, so those statements are recomputed here from the *_ALL
#     tables. A slide whose caption says "phenome-wide" must be drawn from phenome-wide
#     data; shipping the narrow-era picture under a phenome-wide caption is the one
#     failure mode this section exists to prevent.
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 9,
                     "figure.dpi": 300, "savefig.dpi": 300,
                     "savefig.bbox": "tight", "legend.frameon": False})

DECK = os.path.join(FIG, "deck")
os.makedirs(DECK, exist_ok=True)
RISK, PROT = "#c0392b", "#1f6fb4"
CLS_COL = {"NOVEL protein-confirmed": "#7d1128", "NOVEL colocalized": "#c0392b",
           "novel nomination": "#9ec5e8", "recovered known axis": "#8e8e8e",
           "MHC-caution": "#d9d2c5"}
# the ten genes the novelty engine treats as already-drugged axes, with the drug class
# that makes them known. Used only to label the positive-control figure.
KNOWN_DRUG = {"IL6ST": "IL-6 axis · tocilizumab", "IL6R": "IL-6R · sarilumab",
              "CTLA4": "abatacept", "TNFRSF1A": "TNF · etanercept",
              "TNFRSF1B": "TNF · etanercept", "TNFSF14": "TNF superfamily",
              "TNFRSF14": "TNF superfamily", "IL4": "IL-4 axis · dupilumab",
              "TYK2": "deucravacitinib", "JAK2": "JAK inhibitors"}


def _save(fig, name):
    p = os.path.join(DECK, name)
    fig.savefig(p)
    plt.close(fig)
    print(f"  built {name}")
    return p


def _short(s, n):
    """Truncate at a word boundary with an ellipsis. Hard slicing produced labels like
    'Second line medication for Crohn's disea', which reads as a typo rather than a cut."""
    s = str(s)
    if len(s) <= n:
        return s
    cut = s[:n].rsplit(" ", 1)[0]
    return (cut if len(cut) >= n * 0.6 else s[:n]).rstrip(" ,;") + "…"


def _plural(n, word):
    return f"{n} {word}" + ("" if n == 1 else "s")


def _below(ax, ncol=3, size=7.4):
    """Legend parked under the axes. Inside the axes it collided with the bars on every
    ranked chart here, and 'best' just moved the collision around."""
    ax.legend(fontsize=size, ncol=ncol, loc="upper left",
              bbox_to_anchor=(0.0, -0.115), borderaxespad=0)


def _despine(ax, keep=("left", "bottom")):
    for s in ("top", "right", "left", "bottom"):
        if s not in keep:
            ax.spines[s].set_visible(False)


def build_direction_figure():
    g = (NOV.assign(risk=NOV["OR"] > 1)
            .groupby("disease_system")
            .agg(n=("OR", "size"), risk=("risk", "sum")))
    g["prot"] = g["n"] - g["risk"]
    g = g.sort_values("n")
    fig, axes = plt.subplots(1, 2, figsize=(13.2, 5.6),
                             gridspec_kw={"width_ratios": [1.28, 1]})
    ax = axes[0]
    y = np.arange(len(g))
    ax.barh(y, g["risk"], height=.68, color="#c0392b", label="risk-increasing (OR > 1)")
    ax.barh(y, g["prot"], height=.68, left=g["risk"], color="#1f6fb4",
            label="protective (OR < 1)")
    for i, r in enumerate(g.itertuples()):
        ax.text(r.n + max(g["n"]) * .012, i, f"{r.n}   ({100*r.prot/r.n:.0f}% protective)",
                va="center", fontsize=8.2, color="#444")
    ax.set_yticks(y); ax.set_yticklabels(g.index, fontsize=9)
    ax.set_xlabel("causal protein–disease pairs (FDR < 5 %)")
    ax.set_xlim(0, max(g["n"]) * 1.42)
    ax.legend(fontsize=8.5, loc="lower right")
    ax.set_title("A · Direction of effect by disease system", loc="left", fontweight="bold")
    for s in ("top", "right"): ax.spines[s].set_visible(False)

    ax = axes[1]
    cls = (NOV.assign(risk=NOV["OR"] > 1).groupby("immune_class")
              .agg(n=("OR", "size"), risk=("risk", "sum")))
    cls["prot"] = cls["n"] - cls["risk"]
    cls = cls[cls["n"] >= 5].sort_values("n")
    y = np.arange(len(cls))
    ax.barh(y, 100 * cls["risk"] / cls["n"], height=.68, color="#c0392b")
    ax.barh(y, 100 * cls["prot"] / cls["n"], height=.68,
            left=100 * cls["risk"] / cls["n"], color="#1f6fb4")
    ax.axvline(50, color="k", ls="--", lw=.9)
    for i, r in enumerate(cls.itertuples()):
        ax.text(101.5, i, f"n={r.n}", va="center", fontsize=8.2, color="#444")
    ax.set_yticks(y); ax.set_yticklabels(cls.index, fontsize=9)
    ax.set_xlabel("% of causal pairs")
    ax.set_xlim(0, 116)
    ax.set_title("B · Direction by immune protein class", loc="left", fontweight="bold")
    for s in ("top", "right"): ax.spines[s].set_visible(False)
    fig.tight_layout(w_pad=2.4)
    return _save(fig, "DECK_direction_summary.png")


# ---------------------------------------------------------------- positive controls
def build_positive_controls():
    """Known drug axes the pipeline recovered blind, across the whole phenome.

    The archival positive-control figure was drawn when the scan covered 13 curated
    endpoints and could therefore only show three axes. Phenome-wide the same ten
    already-drugged genes recover far more endpoints, which is a much stronger
    calibration statement.
    """
    K = NOV[NOV["category_label"] == "recovered known axis"].copy()
    K["nlp"] = -np.log10(K["FDR"].clip(lower=1e-300))
    top = K.sort_values("nlp", ascending=False).head(16).iloc[::-1]

    fig, axes = plt.subplots(1, 2, figsize=(13.2, 5.7),
                             gridspec_kw={"width_ratios": [1.72, 1]})
    ax = axes[0]
    y = np.arange(len(top))
    ax.barh(y, top["nlp"], height=.7,
            color=[RISK if o > 1 else PROT for o in top["OR"]])
    for i, r in enumerate(top.itertuples()):
        bits = [f"OR {r.OR:.2f}"]
        if pd.notna(r.PP_H4):
            bits.append(f"PP.H4 {r.PP_H4:.2f}")
        ax.text(r.nlp + top["nlp"].max() * .015, i, "   ".join(bits),
                va="center", fontsize=7.6, color="#444")
    ax.set_yticks(y)
    ax.set_yticklabels([f"{r.gene_symbol} → {_short(r.disease, 40)}" for r in top.itertuples()],
                       fontsize=8)
    ax.set_xlim(0, top["nlp"].max() * 1.38)
    ax.set_xlabel("evidence, -log10 FDR")
    ax.set_title(f"A · Strongest recovered known drug axes ({len(K)} pairs phenome-wide)",
                 loc="left", fontweight="bold", fontsize=10)
    ax.plot([], [], "s", color=RISK, label="risk-increasing")
    ax.plot([], [], "s", color=PROT, label="protective")
    ax.legend(fontsize=8, loc="lower right")
    _despine(ax)

    ax = axes[1]
    g = K.groupby("gene_symbol").agg(n=("OR", "size"),
                                     nd=("disease_system", "nunique")).sort_values("n")
    y = np.arange(len(g))
    ax.barh(y, g["n"], height=.62, color="#8e8e8e")
    for i, (gene, r) in enumerate(g.iterrows()):
        ax.text(r["n"] + g["n"].max() * .02, i,
                f"{KNOWN_DRUG.get(gene, '')}  ·  {_plural(int(r['nd']), 'disease system')}",
                va="center", fontsize=7.8, color="#444")
    ax.set_yticks(y); ax.set_yticklabels(g.index, fontsize=9)
    ax.set_xlim(0, g["n"].max() * 2.05)
    ax.set_xlabel("endpoints recovered")
    ax.set_title("B · Recovery per already-drugged gene", loc="left",
                 fontweight="bold", fontsize=10)
    _despine(ax)
    fig.tight_layout(w_pad=2.2)
    return _save(fig, "DECK_positive_controls.png")


# ---------------------------------------------------------------- novel nominations
def build_novel_nominations():
    """The primary output: causal + colocalised pairs with no approved drug on that axis."""
    N = NOV[NOV["category_label"].isin(
        ["NOVEL protein-confirmed", "NOVEL colocalized"])].copy()
    top = N.sort_values("novelty_priority", ascending=False).head(20).iloc[::-1]

    fig, axes = plt.subplots(1, 2, figsize=(13.2, 5.8),
                             gridspec_kw={"width_ratios": [1.5, 1]})
    ax = axes[0]
    y = np.arange(len(top))
    ax.barh(y, top["novelty_priority"], height=.7,
            color=[CLS_COL[c] for c in top["category_label"]])
    for i, r in enumerate(top.itertuples()):
        mark = "★" if r.two_population_validated else ""
        ax.text(r.novelty_priority + top["novelty_priority"].max() * .015, i,
                f"OR {r.OR:.2f}   PP.H4 {r.PP_H4:.2f}  {mark}",
                va="center", fontsize=7.6, color="#444")
    ax.set_yticks(y)
    ax.set_yticklabels([f"{r.gene_symbol} → {_short(r.disease, 38)}" for r in top.itertuples()],
                       fontsize=8)
    ax.set_xlim(0, top["novelty_priority"].max() * 1.34)
    ax.set_xlabel("novelty priority score")
    ax.set_title(f"A · Top 20 of {len(N)} novel colocalised nominations",
                 loc="left", fontweight="bold", fontsize=10)
    for lab in ("NOVEL protein-confirmed", "NOVEL colocalized"):
        ax.plot([], [], "s", color=CLS_COL[lab], label=lab)
    ax.plot([], [], " ", label="★ two-population replicated")
    _below(ax)
    _despine(ax)

    ax = axes[1]
    piv = (N.pivot_table(index="disease_system", columns="category_label",
                         values="OR", aggfunc="size").fillna(0))
    piv = piv.loc[piv.sum(1).sort_values().index]
    left = np.zeros(len(piv))
    for c in ["NOVEL colocalized", "NOVEL protein-confirmed"]:
        if c in piv:
            ax.barh(np.arange(len(piv)), piv[c], left=left, height=.68,
                    color=CLS_COL[c], label=c)
            left = left + piv[c].values
    for i, v in enumerate(left):
        ax.text(v + left.max() * .02, i, f"{int(v)}", va="center", fontsize=8, color="#444")
    ax.set_yticks(np.arange(len(piv))); ax.set_yticklabels(piv.index, fontsize=8.5)
    ax.set_xlim(0, left.max() * 1.22)
    ax.set_xlabel("novel colocalised pairs")
    ax.set_title("B · Where the novel signal sits", loc="left",
                 fontweight="bold", fontsize=10)
    ax.legend(fontsize=7.8, loc="lower right")
    _despine(ax)
    fig.tight_layout(w_pad=2.2)
    return _save(fig, "DECK_novel_nominations.png")


# ---------------------------------------------------------------- novelty engine
def build_novelty_engine():
    """Anatomy of the score: what each component actually contributes, phenome-wide."""
    comp = ["s_causal", "s_coloc", "s_pleio", "s_drug", "s_cell", "s_protein", "s_repl"]
    nice = {"s_causal": "causal strength", "s_coloc": "colocalisation",
            "s_pleio": "cross-system breadth", "s_drug": "druggability",
            "s_cell": "immune-cell source", "s_protein": "protein confirmation",
            "s_repl": "two-population replication"}
    cols = plt.cm.viridis(np.linspace(.1, .92, len(comp)))
    top = NOV.sort_values("novelty_priority", ascending=False).head(18).iloc[::-1]

    fig, axes = plt.subplots(1, 2, figsize=(13.2, 5.9),
                             gridspec_kw={"width_ratios": [1.45, 1]})
    ax = axes[0]
    y = np.arange(len(top))
    left = np.zeros(len(top))
    for c, col in zip(comp, cols):
        ax.barh(y, top[c], left=left, height=.72, color=col, label=nice[c])
        left = left + top[c].values
    pen = -(top["p_known"] + top["p_mhc"]).values
    ax.barh(y, pen, height=.72, color="#b0b0b0", label="penalties (known axis / MHC)")
    ax.axvline(0, color="k", lw=.8)
    for i, r in enumerate(top.itertuples()):
        ax.text(left[i] + left.max() * .015, i, f"{r.novelty_priority:.2f}",
                va="center", fontsize=7.8, fontweight="bold", color="#333")
    ax.set_yticks(y)
    ax.set_yticklabels([f"{r.gene_symbol} → {_short(r.disease, 34)}" for r in top.itertuples()],
                       fontsize=8)
    ax.set_xlim(min(pen.min() * 1.15, -0.3), left.max() * 1.16)
    ax.set_xlabel("score contribution")
    ax.set_title("A · How the top-ranked pairs earn their score", loc="left",
                 fontweight="bold", fontsize=10)
    _below(ax, ncol=4, size=7.2)
    _despine(ax)

    ax = axes[1]
    order = [c for c in ["NOVEL protein-confirmed", "NOVEL colocalized",
                         "novel nomination", "recovered known axis", "MHC-caution"]
             if c in set(NOV["category_label"])]
    m = NOV.groupby("category_label")[comp].mean().reindex(order)
    left = np.zeros(len(m))
    for c, col in zip(comp, cols):
        ax.barh(np.arange(len(m)), m[c], left=left, height=.66, color=col)
        left = left + m[c].values
    m2 = NOV.groupby("category_label")[["p_known", "p_mhc"]].mean().reindex(order)
    ax.barh(np.arange(len(m)), -(m2.sum(1)).values, height=.66, color="#b0b0b0")
    ax.axvline(0, color="k", lw=.8)
    counts = NOV["category_label"].value_counts()
    ax.set_yticks(np.arange(len(m)))
    ax.set_yticklabels([f"{c}\n(n = {counts[c]})" for c in m.index], fontsize=8.2)
    ax.set_xlabel("mean score contribution")
    ax.set_title(f"B · Component profile of each class ({len(NOV):,} pairs)",
                 loc="left", fontweight="bold", fontsize=10)
    _despine(ax)
    fig.tight_layout(w_pad=2.2)
    return _save(fig, "DECK_novelty_engine.png")


# ---------------------------------------------------------------- phenome volcano
def _volcano_data():
    """1.66 M MR tests will not fit comfortably in a figure or in memory twice, so the
    full scan is reduced once to (every significant test + a 2 % random sample of the
    rest) and cached. The sample is only ever used to draw the grey background cloud;
    every counted number comes from the significant set."""
    cache = os.path.join(DECK, "_volcano_cache.parquet")
    meta = os.path.join(DECK, "_volcano_counts.tsv")
    meta2 = os.path.join(DECK, "_volcano_counts_class.tsv")
    scan = os.path.join(DECK, "_scan_totals.tsv")
    if all(os.path.exists(p) for p in (cache, meta, meta2, scan)):
        return (pd.read_parquet(cache), pd.read_csv(meta, sep="\t", index_col=0),
                pd.read_csv(meta2, sep="\t", index_col=0),
                pd.read_csv(scan, sep="\t", index_col=0)["value"])
    src = os.path.join(GC, "cis_MR_ALL_finngen_results.tsv")
    use = ["gene_symbol", "phenotype", "phenocode", "category", "OR", "MR_p", "FDR",
           "immune_class"]
    keep, ntot = [], 0
    tested, hits, ctested, chits = {}, {}, {}, {}
    genes, phenos = set(), set()
    # counted on phenocode, not the display name: two FinnGen codes can share a name,
    # which made the manuscript and the methodology quote 379 vs 381 for the same set
    hgenes, hcodes, hchap = set(), set(), set()
    rng = np.random.default_rng(0)

    def bump(d, s):
        for k, v in s.value_counts().items():
            d[k] = d.get(k, 0) + int(v)

    for ch in pd.read_csv(src, sep="\t", usecols=use, chunksize=400_000):
        ntot += len(ch)
        genes.update(ch["gene_symbol"].unique())
        phenos.update(ch["phenotype"].unique())
        bump(tested, ch["category"]); bump(ctested, ch["immune_class"])
        sig = ch[ch["FDR"] < 0.05]
        bump(hits, sig["category"]); bump(chits, sig["immune_class"])
        hgenes.update(sig["gene_symbol"].unique()); hcodes.update(sig["phenocode"].unique())
        hchap.update(sig["category"].dropna().unique())
        bg = ch[ch["FDR"] >= 0.05]
        bg = bg.iloc[rng.random(len(bg)) < 0.02]
        keep.append(pd.concat([sig, bg]))
    d = pd.concat(keep, ignore_index=True)
    d.to_parquet(cache, index=False)
    cnt = pd.DataFrame({"tested": pd.Series(tested), "hits": pd.Series(hits)}).fillna(0)
    cnt.to_csv(meta, sep="\t")
    ccnt = pd.DataFrame({"tested": pd.Series(ctested), "hits": pd.Series(chits)}).fillna(0)
    ccnt.to_csv(meta2, sep="\t")
    tot = pd.Series({"tests": ntot, "genes": len(genes), "endpoints": len(phenos),
                     "hits": int(cnt["hits"].sum()), "chapters": len(tested),
                     "hit_genes": len(hgenes), "hit_endpoints": len(hcodes),
                     "hit_chapters": len(hchap)}, name="value")
    tot.to_frame().to_csv(scan, sep="\t")
    print(f"  scan cache built from {ntot:,} MR tests")
    return d, cnt, ccnt, tot


# ---------------------------------------------------------------- MR design
def build_mr_design():
    """The design schematic, stated with the numbers of the actual whole-phenome run.

    The archival version of this figure was drawn against 13 curated autoimmune GWAS
    and 8,749 tests; the deck must show the scan that the rest of the deck reports.
    """
    _, cnt, ccnt, tot = _volcano_data()
    fig, axes = plt.subplots(1, 2, figsize=(13.2, 5.3),
                             gridspec_kw={"width_ratios": [1.32, 1]})
    from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
    ax = axes[0]; ax.axis("off")
    steps = [(f"{int(tot['genes'])}\nplasma immune\nproteins",
              "strongest cis-eQTL\nper protein, eQTLGen"),
             (f"{int(tot['endpoints']):,}\nFinnGen R12\nendpoints",
              f"every chapter of the\nphenome ({int(tot['chapters'])} chapters)"),
             (f"{int(tot['tests']):,}\nWald-ratio\nMR tests",
              "BH-FDR applied across\nthe whole phenome"),
             (f"{int(tot['hits']):,}\ncausal tests\nFDR < 5 %",
              f"{N_PAIRS:,} unique protein–\ndisease pairs"),
             ("7 evidence\nlayers",
              f"{N_COLOC} colocalised ·\n{N_REPL} replicated")]
    cols = plt.cm.Spectral(np.linspace(.08, .92, len(steps)))
    n = len(steps)
    w, gap = 0.163, 0.046
    for i, ((head, sub), c) in enumerate(zip(steps, cols)):
        x = i * (w + gap)
        ax.add_patch(FancyBboxPatch((x, 0.50), w, 0.30, boxstyle="round,pad=0.012",
                                    fc=c, ec="#333", lw=.9, alpha=.92))
        ax.text(x + w / 2, 0.65, head, ha="center", va="center", fontsize=8.4,
                fontweight="bold")
        ax.text(x + w / 2, 0.42, sub, ha="center", va="top", fontsize=7.2, color="#444")
        if i < n - 1:
            ax.add_patch(FancyArrowPatch((x + w + .004, 0.65), (x + w + gap - .004, 0.65),
                                         arrowstyle="-|>", mutation_scale=11, color="#888"))
    ax.set_xlim(-0.01, n * (w + gap) - gap + 0.01); ax.set_ylim(0.12, 1.0)
    ax.set_title("A · Whole-phenome causal-inference design", loc="left",
                 fontweight="bold", fontsize=10)

    ax = axes[1]
    e = ccnt[ccnt["tested"] >= 500].copy()
    e["rate"] = 100 * e["hits"] / e["tested"]
    e = e.sort_values("rate")
    y = np.arange(len(e))
    ax.barh(y, e["rate"], height=.66, color=plt.cm.viridis(np.linspace(.2, .85, len(e))))
    for i, r in enumerate(e.itertuples()):
        ax.text(r.rate + e["rate"].max() * .02, i,
                f"{int(r.hits):,} / {int(r.tested):,}", va="center", fontsize=7.6,
                color="#444")
    ax.set_yticks(y); ax.set_yticklabels(e.index, fontsize=8.5)
    ax.set_xlim(0, e["rate"].max() * 1.42)
    ax.set_xlabel("% of tests significant at FDR < 5 %")
    ax.set_title("B · Causal yield by immune protein class", loc="left",
                 fontweight="bold", fontsize=10)
    _despine(ax)
    fig.tight_layout(w_pad=2.2)
    return _save(fig, "DECK_mr_design.png")


def build_phenome_volcano():
    d, cnt, _ccnt, tot = _volcano_data()
    d = d[d["OR"].between(1e-6, 1e6) & d["MR_p"].gt(0)]
    d["lor"] = np.log(d["OR"])
    d["nlp"] = -np.log10(d["MR_p"].clip(lower=1e-300))
    q = d["lor"].abs().quantile(.999)
    d = d[d["lor"].abs() <= q]
    sig = d[d["FDR"] < 0.05]
    bg = d[d["FDR"] >= 0.05]

    fig, axes = plt.subplots(1, 2, figsize=(13.2, 5.7),
                             gridspec_kw={"width_ratios": [1.15, 1]})
    ax = axes[0]
    ax.scatter(bg["lor"], bg["nlp"], s=2, color="#c9c9d0", alpha=.35,
               edgecolors="none", rasterized=True)
    ax.scatter(sig["lor"], sig["nlp"], s=6,
               color=np.where(sig["OR"] > 1, RISK, PROT), alpha=.75,
               edgecolors="none", rasterized=True)
    ax.axvline(0, color="k", lw=.7)
    ax.axhline(-np.log10(sig["MR_p"].max()), color="k", ls="--", lw=.8)
    ax.text(q * .98, -np.log10(sig["MR_p"].max()), " FDR 5 %", fontsize=8,
            ha="right", va="bottom")
    for r in sig.nlargest(8, "nlp").itertuples():
        ax.annotate(f"{r.gene_symbol} → {_short(r.phenotype, 24)}", (r.lor, r.nlp),
                    fontsize=7, xytext=(6 if r.lor < 0 else -6, 3),
                    textcoords="offset points", ha="left" if r.lor < 0 else "right",
                    color=RISK if r.OR > 1 else PROT)
    ax.set_xlabel("causal effect, log OR per unit genetically-proxied expression")
    ax.set_ylabel("-log10 P")
    ax.set_title(f"A · {int(tot['tests']):,} MR tests · {int(tot['hits']):,} causal at FDR < 5 %",
                 loc="left", fontweight="bold", fontsize=10)
    ax.plot([], [], "o", ms=4, color=RISK, label="risk-increasing")
    ax.plot([], [], "o", ms=4, color=PROT, label="protective")
    ax.plot([], [], "o", ms=3, color="#c9c9d0", label="not significant (2 % shown)")
    _below(ax)
    _despine(ax)

    ax = axes[1]
    c = cnt[cnt["hits"] > 0].copy()
    c["rate"] = 100 * c["hits"] / c["tested"]
    c = c.sort_values("hits").tail(20)
    y = np.arange(len(c))
    ax.barh(y, c["hits"], height=.68, color="#7d1128")
    for i, r in enumerate(c.itertuples()):
        ax.text(r.hits + c["hits"].max() * .02, i,
                f"{r.rate:.2f} % of {int(r.tested):,} tests", va="center",
                fontsize=7.6, color="#444")
    ax.set_yticks(y)
    ax.set_yticklabels([_short(i, 34) for i in c.index], fontsize=7.8)
    ax.set_xlim(0, c["hits"].max() * 1.55)
    ax.set_xlabel("causal tests, FDR < 5 %")
    ax.set_title("B · Causal yield per FinnGen chapter (top 20)", loc="left",
                 fontweight="bold", fontsize=10)
    _despine(ax)
    fig.tight_layout(w_pad=2.2)
    return _save(fig, "DECK_phenome_volcano.png")


# ---------------------------------------------------------------- pleiotropy
def build_pleiotropy():
    """Which proteins act across many disease systems at once — whole phenome."""
    ns = NOV.groupby("gene_symbol")["disease_system"].nunique().sort_values(ascending=False)
    genes = ns.head(26).index[::-1]
    piv = (NOV[NOV["gene_symbol"].isin(genes)]
           .pivot_table(index="gene_symbol", columns="disease_system",
                        values="OR", aggfunc="size").fillna(0).reindex(genes))
    piv = piv[piv.sum(0).sort_values(ascending=False).index]

    fig, axes = plt.subplots(1, 2, figsize=(13.2, 6.0),
                             gridspec_kw={"width_ratios": [1.75, 1]})
    ax = axes[0]
    im = ax.imshow(piv.values, aspect="auto", cmap="YlOrRd", vmin=0,
                   vmax=np.percentile(piv.values[piv.values > 0], 92))
    for i in range(piv.shape[0]):
        for j in range(piv.shape[1]):
            v = int(piv.values[i, j])
            if v:
                ax.text(j, i, v, ha="center", va="center", fontsize=6.4,
                        color="white" if v > piv.values.max() * .55 else "#333")
    ax.set_xticks(np.arange(piv.shape[1]))
    ax.set_xticklabels(piv.columns, rotation=38, ha="right", fontsize=7.6)
    ax.set_yticks(np.arange(piv.shape[0]))
    ax.set_yticklabels(piv.index, fontsize=7.6)
    ax.set_title("A · Causal pairs per protein per disease system (26 broadest proteins)",
                 loc="left", fontweight="bold", fontsize=10)
    cb = fig.colorbar(im, ax=ax, fraction=.022, pad=.012)
    cb.ax.tick_params(labelsize=7)
    cb.set_label("causal pairs", fontsize=7.5)

    ax = axes[1]
    h = ns.value_counts().sort_index()
    ax.bar(h.index, h.values, color="#7d1128", width=.72)
    for x, v in h.items():
        ax.text(x, v + h.max() * .02, str(v), ha="center", fontsize=7.6, color="#444")
    ax.set_xlabel("disease systems reached by one protein")
    ax.set_ylabel("number of proteins")
    ax.set_ylim(0, h.max() * 1.18)
    ax.set_title(f"B · Breadth distribution ({NOV['gene_symbol'].nunique()} causal proteins)",
                 loc="left", fontweight="bold", fontsize=10)
    med = ns.median()
    ax.axvline(med, color="k", ls="--", lw=.9)
    ax.text(med + .55, h.max() * .80, f"median {med:.0f} systems", fontsize=8)
    _despine(ax)
    fig.tight_layout(w_pad=2.4)
    return _save(fig, "DECK_pleiotropy.png")


# ---------------------------------------------------------------- cell source
def build_cellsource():
    """Which immune lineage expresses the causal proteins, whole phenome."""
    ann = pd.read_csv(os.path.join(ROOT, "02_data_processed",
                                   "plasma_immune_protein_annotation.tsv"), sep="\t")
    src = dict(zip(ann["gene_symbol"], ann["immune_source_cells"].fillna("")))
    rows = []
    for r in NOV.itertuples():
        for c in str(src.get(r.gene_symbol, "")).split(";"):
            c = c.strip()
            if c:
                rows.append((c, r.disease_system, r.OR))
    L = pd.DataFrame(rows, columns=["lineage", "disease_system", "OR"])
    piv = (L.pivot_table(index="lineage", columns="disease_system", values="OR",
                         aggfunc="size").fillna(0))
    piv = piv.loc[piv.sum(1).sort_values(ascending=False).index]
    piv = piv[piv.sum(0).sort_values(ascending=False).index]
    pct = 100 * piv.div(piv.sum(0), axis=1)

    fig, axes = plt.subplots(1, 2, figsize=(13.2, 5.8),
                             gridspec_kw={"width_ratios": [1.7, 1]})
    ax = axes[0]
    im = ax.imshow(pct.values, aspect="auto", cmap="Blues", vmin=0,
                   vmax=np.percentile(pct.values, 96))
    for i in range(piv.shape[0]):
        for j in range(piv.shape[1]):
            v = int(piv.values[i, j])
            if v:
                ax.text(j, i, v, ha="center", va="center", fontsize=6.4,
                        color="white" if pct.values[i, j] > pct.values.max() * .55 else "#333")
    ax.set_xticks(np.arange(piv.shape[1]))
    ax.set_xticklabels(piv.columns, rotation=38, ha="right", fontsize=7.6)
    ax.set_yticks(np.arange(piv.shape[0]))
    ax.set_yticklabels(piv.index, fontsize=8)
    ax.set_title("A · Causal pairs by immune lineage of origin and disease system",
                 loc="left", fontweight="bold", fontsize=10)
    cb = fig.colorbar(im, ax=ax, fraction=.022, pad=.012)
    cb.ax.tick_params(labelsize=7)
    cb.set_label("% of that system's pairs", fontsize=7.5)

    ax = axes[1]
    g = L.assign(risk=L["OR"] > 1).groupby("lineage").agg(n=("OR", "size"),
                                                          risk=("risk", "sum"))
    g["prot"] = g["n"] - g["risk"]
    g = g.sort_values("n")
    y = np.arange(len(g))
    ax.barh(y, g["risk"], height=.66, color=RISK, label="risk-increasing")
    ax.barh(y, g["prot"], left=g["risk"], height=.66, color=PROT, label="protective")
    for i, r in enumerate(g.itertuples()):
        ax.text(r.n + g["n"].max() * .02, i, f"{r.n}  ({100*r.prot/r.n:.0f}% prot.)",
                va="center", fontsize=7.8, color="#444")
    ax.set_yticks(y); ax.set_yticklabels(g.index, fontsize=8.5)
    ax.set_xlim(0, g["n"].max() * 1.42)
    ax.set_xlabel("causal protein–disease pairs")
    ax.set_title("B · Direction of effect within each lineage", loc="left",
                 fontweight="bold", fontsize=10)
    ax.legend(fontsize=8, loc="lower right")
    _despine(ax)
    fig.tight_layout(w_pad=2.4)
    return _save(fig, "DECK_cellsource.png")


# ---------------------------------------------------------------- evidence ladder
def build_evidence_ladder():
    """How much of the causal set survives each independent confirmation.

    The archival panel D of the intelligence layer counted the replication bar with an
    exact string match on "replicated", which misses the 89 pairs labelled
    "replicated (FinnGen + UK Biobank)" and therefore reported 4 instead of 93. It is
    recounted here from the same table with a prefix match.
    """
    t = pd.read_csv(os.path.join(ROOT, "09_tables",
                                 "T6_disease_intelligence_final_table_ALL.tsv"), sep="\t")
    rep = t["Replication"].astype(str).str.lower().str.startswith("replicated")
    bars = [("causal\nMR, FDR < 5 %", int((t["MR_support"] == "yes").sum())),
            ("colocalised\nPP.H4 ≥ 0.8",
             int(t["Coloc_support"].str.startswith("yes").sum())),
            ("replicated\nFinland → England", int(rep.sum())),
            ("concordant\nplasma pQTL",
             int(t["pQTL_support"].str.startswith("yes").sum())),
            ("protein-level\ncausal", int((t["Protein_level_causal"] == "yes").sum()))]

    fig, axes = plt.subplots(1, 2, figsize=(13.2, 5.4),
                             gridspec_kw={"width_ratios": [1.15, 1]})
    ax = axes[0]
    labs, vals = zip(*bars)
    cols = ["#8ecae6", "#219ebc", "#126782", "#0d4f66", "#023047"]
    ax.bar(np.arange(len(vals)), vals, color=cols, width=.66, edgecolor="none")
    for i, v in enumerate(vals):
        ax.text(i, v + max(vals) * .02, f"{v:,}\n{100*v/vals[0]:.0f} % of causal",
                ha="center", fontsize=8.2, fontweight="bold", color="#333")
    ax.set_xticks(np.arange(len(labs)))
    ax.set_xticklabels(labs, fontsize=7.8)
    ax.set_ylim(0, max(vals) * 1.22)
    ax.set_ylabel("protein–disease pairs")
    ax.set_title("A · What survives each independent layer", loc="left",
                 fontweight="bold", fontsize=10)
    _despine(ax)

    ax = axes[1]
    lab = t.groupby("Novelty_tier")["Novelty_tier_label"].first()
    cnt = t["Novelty_tier"].value_counts().sort_index()
    y = np.arange(len(cnt))
    ax.barh(y, cnt.values, height=.66,
            color=plt.cm.viridis(np.linspace(.15, .85, len(cnt))))
    for i, v in enumerate(cnt.values):
        ax.text(v + cnt.max() * .015, i, f"{v:,}", va="center", fontsize=8.5,
                fontweight="bold", color="#444")
    ax.set_yticks(y)
    ax.set_yticklabels([f"tier {i} · {lab[i]}" for i in cnt.index], fontsize=8.5)
    ax.set_xlim(0, cnt.max() * 1.18)
    ax.set_xlabel("protein–disease pairs")
    ax.invert_yaxis()
    ax.set_title("B · Novelty tier of every causal pair", loc="left",
                 fontweight="bold", fontsize=10)
    _despine(ax)
    fig.tight_layout(w_pad=2.4)
    return _save(fig, "DECK_evidence_ladder.png")


print("[54] building slide-native whole-phenome figures ...")
build_direction_figure()
build_mr_design()
build_positive_controls()
build_novel_nominations()
build_novelty_engine()
build_phenome_volcano()
build_pleiotropy()
build_cellsource()
build_evidence_ladder()

# the scan totals are counted while streaming the full MR table, so every headline
# number on the cover comes from the same pass that drew the volcano
_SCAN = _volcano_data()[3]
N_TESTS, N_ENDP, N_CHAP = (int(_SCAN["tests"]), int(_SCAN["endpoints"]),
                           int(_SCAN["chapters"]))


# ================================================================= MAIN DECK
def F(sub, name):
    return os.path.join(FIG, sub, name)


MAIN = [
 ("SECTION", "The resource", "A causal map from the plasma immunome to the disease phenome",
  f"672 plasma immune proteins instrumented with cis-eQTLs and tested against all {N_ENDP:,} "
  f"endpoints of the FinnGen R12 phenome ({N_CHAP} disease chapters), then filtered through six "
  f"further evidence layers.",
  [f"{N_TESTS:,} Mendelian-randomisation tests",
   f"{N_PAIRS:,} causal protein–disease pairs at FDR < 5 %",
   f"{N_COLOC} colocalised (PP.H4 ≥ 0.8) · {N_REPL} replicated in a second population",
   "Every figure reproducible from public data — no login, no restricted access"]),

 ("nature", "Figure1_design_curation.png", "#",
  "Curation of the plasma immunome",
  "Three orthogonal annotation sources define the protein universe",
  "The plasma immunome is defined as the intersection of proteins that are (a) measurable in "
  "plasma by Olink Explore, (b) annotated as secreted or plasma-detectable in the Human Protein "
  "Atlas, and (c) members of MSigDB C7/C8 immune gene sets. (a) Curation funnel from 2,923 "
  "candidates to the 1,007-protein plasma immunome. (b) Immune class composition. (c) Immune-cell "
  "source of each protein. (d) Co-occurrence of annotation flags — the classes are largely "
  "non-redundant, so the class labels carry independent information."),

 ("nature", "Figure2_druggability_architecture.png", "#",
  "Druggability architecture of the immunome",
  "Where the tractable protein space sits",
  "Tractability of the plasma immunome, split by immune class and by evidence for an existing "
  "drug. This is the denominator against which the causal results are later judged: a causal "
  "protein is only therapeutically actionable if it also sits in a tractable class."),

 ("deck", "DECK_mr_design.png", "#",
  "Mendelian-randomisation design",
  "cis-eQTL instrument → FinnGen R12 outcome → Wald ratio → BH-FDR",
  "(A) The causal-inference design, with the counts of the actual run. For each protein the "
  "strongest cis-eQTL from eQTLGen (n ≈ 31,684) is the instrument, tested against every FinnGen "
  "R12 endpoint by the Wald ratio, with Benjamini–Hochberg correction applied across the entire "
  "phenome rather than within disease chapters — so no chapter is preferentially significant. "
  "(B) Causal yield by immune protein class, expressed as a share of the tests run in that class "
  "so that abundant classes are not mistaken for enriched ones."),

 ("deck", "DECK_positive_controls.png", "#",
  "Positive controls recovered blind",
  "The pipeline rediscovers drug axes it was never told about, phenome-wide",
  f"The ten genes that already carry an approved drug were never given to the pipeline, yet they "
  f"are recovered across {int((NOV.category_label=='recovered known axis').sum())} endpoints of "
  f"the whole phenome. (A) The strongest recovered axes with effect direction and colocalisation "
  f"posterior. (B) Recovery per gene: IL6ST (tocilizumab), CTLA4 (abatacept), TNFRSF1A/1B "
  f"(etanercept) and IL4 (dupilumab) each reappear over several disease systems. Recovering the "
  f"direction as well as the target is the calibration that licenses the novel nominations."),

 ("deck", "DECK_novel_nominations.png", "#",
  "Novel therapeutic nominations",
  "Causal, colocalised, and not yet drugged — across the whole phenome",
  f"Protein–disease pairs that are causal and colocalised (PP.H4 ≥ 0.8) but carry no approved "
  f"drug acting on that axis. (A) The 20 highest-priority nominations of "
  f"{int(NOV.category_label.isin(['NOVEL colocalized','NOVEL protein-confirmed']).sum())}; ★ marks "
  f"pairs that also replicate in a second population. (B) Their distribution across disease "
  f"systems. These are the primary output of the atlas."),

 ("paper_style", "DL2b_uk_replication_expanded.png", "#",
  "Two-population replication",
  "Finland → England, whole phenome, single-cohort UK Biobank only",
  f"Each causal claim is re-tested in UK Biobank with the same instrument: 189 like-for-like "
  f"tests over 62 diseases and 90 genes, of which 162 (86 %) agree in causal direction and "
  f"{N_REPL} also reach P < 0.05 and are flagged two-population validated. Only single-cohort "
  f"UK Biobank GWAS are eligible — several large public meta-analyses of the same endpoints "
  f"silently include FinnGen, which would make replication circular. That exclusion, not signal "
  f"failure, is why the replication counts are conservative."),

 ("deck", "DECK_novelty_engine.png", "#",
  "The novelty engine",
  "Seven evidence components, two penalties, one priority score",
  f"Novelty is scored as causal strength + colocalisation + cross-system breadth + druggability + "
  f"immune-cell support + protein confirmation + replication, penalised for pairs that recover an "
  f"approved drug axis and for pairs in the MHC region where long-range LD defeats "
  f"colocalisation. (A) The component anatomy of the highest-scoring pairs — no pair reaches the "
  f"top on a single component. (B) The mean profile of each class over all {N_PAIRS:,} pairs, "
  f"showing that the classes differ in which evidence they carry, not only in how much."),

 ("deck", "DECK_phenome_volcano.png", "#",
  "Phenome-wide causal landscape",
  "Every protein against every endpoint of FinnGen R12",
  "(A) Volcano of the complete 1,656,872-test scan: effect direction on the x-axis, evidence on "
  "the y-axis. The causal set is dominated by neither risk-increasing nor protective effects, "
  "which is why therapeutic direction must be read protein by protein rather than assumed. "
  "(B) Causal yield per FinnGen chapter, given as a count and as a percentage of the tests "
  "actually run in that chapter, so a large chapter is not mistaken for an enriched one."),

 ("deck", "DECK_pleiotropy.png", "#",
  "Cross-system pleiotropy",
  "Which proteins act on many disease systems at once",
  f"Proteins causal across many unrelated disease systems are down-weighted by the novelty "
  f"engine: broad pleiotropy raises the probability of a horizontal (non-causal) path and lowers "
  f"the specificity of any therapeutic intervention. (A) The 26 broadest proteins against all 14 "
  f"disease systems. (B) The full breadth distribution over the "
  f"{NOV['gene_symbol'].nunique()} causal proteins — most are narrow, so the penalty affects a "
  f"minority of the atlas."),

 ("deck", "DECK_cellsource.png", "#",
  "Immune-cell source of causal proteins",
  "Which lineage the causal signal comes from",
  "Each causal protein is mapped back to the immune lineage that expresses it. (A) Lineage "
  "against disease system, shaded by that lineage's share of the system's causal pairs, so it "
  "shows which arm of the immune system drives each part of the phenome. (B) Direction of effect "
  "within each lineage — no lineage is uniformly harmful, which again argues against blanket "
  "suppression of any single arm."),

 ("deck", "DECK_direction_summary.png", "#",
  "Direction of effect across the phenome",
  "Risk-increasing versus protective, by disease system and by protein class",
  "(A) Every causal pair split by disease system and direction of effect. (B) The same split by "
  "immune protein class. Protective effects are the majority in most systems and in most classes, "
  "which argues directly against broad immunosuppression as a general strategy: the therapeutic "
  "direction has to be read protein by protein. The per-pair ranked version of this map is "
  "Figure 14 of the archival figure set."),

 ("nature", "Figure17_layer_disease_coverage.png", "#",
  "Coverage of the seven evidence layers",
  "How far each layer reaches across the phenome",
  "Not every layer can reach every endpoint: colocalisation needs full summary statistics, "
  "protein confirmation needs a public aptamer, and two-population replication needs an "
  "independent GWAS of the same endpoint to exist. This figure states that coverage honestly "
  "instead of implying uniform evidence."),

 ("nature", "Figure18_panphenome_pqtl_volcano.png", "#",
  "Protein-level MR across the phenome",
  "INTERVAL pQTL exposures, 219 diseases",
  "Whole-phenome MR using plasma protein levels rather than transcript as the exposure: 473 "
  "protein-level tests across 219 diseases, 149 significant at FDR < 5 %."),

 ("nature", "Figure19_eqtl_pqtl_concordance_all.png", "#",
  "Transcript versus protein concordance",
  "Do the two exposures agree?",
  "Direct comparison of the eQTL-based and pQTL-based causal estimate for every pair where both "
  "exist: 412 pairs, of which 224 (54 %) agree in direction and 85 also reach P < 0.05 at the "
  "protein level and are promoted to protein-confirmed.\n\n"
  "Concordance supports the transcript layer as a valid screen. Discordance is informative rather "
  "than a failure: it flags pairs where transcript abundance does not track circulating protein, "
  "which is exactly where a transcript-only atlas would mislead.\n\n"
  "This is also the reason the pQTL layer is used as an arbiter and not as the primary scan — "
  "public aptamer coverage reaches only a minority of the immunome, so running it first would "
  "have discarded most of the phenome before it was ever tested."),

 ("nature", "Figure20_tiers_by_system_all.png", "#",
  "Evidence tiers by disease system",
  "Where the strongest evidence concentrates",
  "The integrated 1–5 evidence tier, broken down by disease system, showing which parts of the "
  "phenome currently carry protein-level or replicated colocalised support."),

 ("nature", "Figure21_novelty_priority_all.png", "#",
  "Whole-phenome novelty priority",
  "The ranked therapeutic short-list",
  "All causal pairs ranked by novelty priority across the whole phenome, the master ranking from "
  "which each disease-specific short-list is drawn."),

 ("nature", "Figure22_pqtl_coloc_all.png", "#",
  "Protein-level colocalisation",
  "Shared causal variants at the protein locus",
  "Colocalisation between the plasma pQTL signal and the disease signal — the strictest "
  "confirmation available from login-free public data, and the criterion for tier 1."),

 ("SECTION", "Focus", "Cardiovascular disease",
  f"The cardiovascular chapter is the largest disease system in the atlas: {CV_N} causal "
  f"protein–disease pairs, {100*CV_N/N_PAIRS:.0f} % of the whole-phenome causal set — and almost "
  f"none of it is currently drugged.",
  [f"{CV_G} plasma immune proteins × {CV_D} FinnGen R12 cardiovascular endpoints",
   f"{CV_COLOC} colocalised · {CV_REPL} replicated Finland → England",
   f"{CV_NOVEL} NOVEL with colocalisation support, versus {CV_KNOWN} recovered known drug axis",
   f"{CV_DRUG} pairs sit on a protein with an existing tractability route"]),

 ("cv_novelty", "CVN1_evidence_funnel.png", "#",
  "Cardiovascular evidence funnel",
  "What survives each layer",
  f"Of 78,605 cis-MR tests against cardiovascular endpoints, {CV_N} are causal at FDR < 5 %, "
  f"{CV_COLOC} colocalise at PP.H4 ≥ 0.8, {CV_REPL} replicate in an independent UK Biobank "
  f"population, and 5 are confirmed at the circulating-protein level. Each layer is an "
  f"independent filter, so the surviving set is the therapeutically actionable core."),

 ("cv_novelty", "CVN2_novelty_classes.png", "#",
  "How novel is the cardiovascular signal?",
  "Engine class composition, and cardiovascular versus the rest of the phenome",
  f"(A) The {CV_N} cardiovascular causal pairs split by novelty class: {CV_NOVEL} NOVEL with "
  f"colocalisation support and only {CV_KNOWN} recovered known drug axis. (B) Cardiovascular "
  f"disease is enriched for novel colocalised signal relative to the rest of the phenome and is "
  f"almost devoid of recovered known axes — it is unexploited therapeutic territory."),

 ("cv_novelty", "CVN3_top25_priority.png", "#",
  "Top 25 novel cardiovascular targets",
  "Ranked by novelty priority",
  "Every bar is a live causal claim carrying a direction of effect, a colocalisation posterior "
  "and, where an independent GWAS exists, a two-population test. SLC12A2 and PPP3R1 dominate the "
  "venous endpoints; PSRC1 and FES the coronary and hypertensive ones."),

 ("cv_novelty", "CVN4_novelty_vs_strength.png", "#",
  "Novelty against causal strength",
  "Novel does not mean weak",
  "Novelty priority plotted against MR evidence. Several of the least previously described "
  "proteins carry the strongest cardiovascular causal evidence in the atlas, so the novel set "
  "cannot be dismissed as the residue left after the strong signals were taken."),

 ("cv_novelty", "CVN5_disease_map.png", "#",
  "Cardiovascular endpoints reached",
  "Not only atherosclerosis",
  "Hypertension, venous disease, atrial fibrillation and revascularisation endpoints each carry "
  "independent plasma-immune causal architecture. The venous endpoints in particular are "
  "dominated by novel colocalised proteins with essentially no prior immune-therapeutic "
  "literature."),

 ("cv_novelty", "CVN6_direction_action.png", "#",
  "Therapeutic direction and implied action",
  "The protective majority",
  f"(A) Distribution of causal effect direction: {int((CV.OR<1).sum())} of {CV_N} cardiovascular "
  f"pairs are protective versus {int((CV.OR>1).sum())} risk-increasing. (B) Implied therapeutic "
  f"action by novelty class. Because protective effects predominate, broad immunosuppression "
  f"would be expected to harm more of this axis than it helps."),

 ("cv_novelty", "CVN7_tiers_druggability.png", "#",
  "Evidence tier and druggability",
  "What could be acted on now",
  f"(A) Integrated evidence tier; tier 1–2 pairs carry protein-level or replicated colocalised "
  f"support. (B) Druggability: {CV_DRUG} pairs have a tractability route and "
  f"{int((CV.fda_target==1).sum())} sit on proteins already targeted by an approved drug in "
  f"another indication — immediate repurposing candidates."),

 ("cv_novelty", "CVN8_case_studies.png", "#",
  "Worked cardiovascular case studies",
  "The six highest-priority novel proteins",
  "For each protein, every cardiovascular endpoint it causes, with the colocalisation posterior "
  "printed above each point. Red = risk-increasing, blue = protective. Consistency of direction "
  "across related endpoints is itself evidence: a horizontal-pleiotropy artefact would not "
  "respect disease boundaries this cleanly."),

 ("heart", "HEART2_chd_triangulation.png", "#",
  "Coronary disease triangulation",
  "Three independent lines of evidence on one axis",
  "cis-eQTL MR, colocalisation and two-population replication triangulated on coronary heart "
  "disease. Agreement across methods that fail in different ways is stronger evidence than any "
  "single method at a smaller p-value."),

 ("heart", "HEART3_druggable_targets.png", "#",
  "Druggable cardiovascular targets",
  "The actionable short-list",
  "Cardiovascular causal proteins that are tractable, ordered by evidence. This is the handover "
  "point from genetics to a drug-discovery programme."),

 ("SECTION", "Beyond the causal map", "The molecular and predictive layers",
  "The atlas does not stop at causality: the same instruments are used to ask how the protein "
  "changes the immune system itself, and whether the causal set carries predictive information.",
  ["Immune-cell counts, cell fractions and CRP as intermediate phenotypes",
   "A plasma immune risk score built only from causally-supported proteins",
   "Concordance between causal direction and predictive weight"]),

 ("paper_style", "R2_cellcount_manhattan.png", "#",
  "Immune-cell and inflammation layer",
  "The same instruments against blood cell traits and CRP",
  "Phenome-wide scan of the causal proteins against blood cell counts, cell fractions and CRP. A "
  "protein that causes disease and also moves the corresponding immune cell population has a "
  "mechanistic route, not just a statistical association."),

 ("paper_style", "R3_cellcount_direction.png", "#",
  "Direction of the cell-trait effects",
  "Mechanistic coherence",
  "Direction of effect on immune cell traits, compared with the direction of the disease effect. "
  "Coherent pairs — protein raises the cell population and raises disease risk — are the most "
  "mechanistically interpretable nominations."),

 ("deck", "DECK_evidence_ladder.png", "#",
  "The evidence ladder",
  "How much of the causal set survives each independent confirmation",
  "(A) Every causal pair carried through the confirmation layers. Colocalisation retains 41 % of "
  "the causal set; two-population replication and protein-level pQTL each retain about 9 %. The "
  "fall-off is dominated by coverage — an endpoint with no independent GWAS or a protein with no "
  "public aptamer cannot be confirmed even when the causal claim is correct — so these are lower "
  "bounds, not failure rates. (B) The resulting novelty tier of all 1,016 pairs: tier 1 is the "
  "known-drug positive controls, tier 2 the MHC pairs held at nomination, tiers 4–5 the "
  "prioritised and protein-level novel targets."),

 ("intelligence_layer", "IL_panelE_novelty_map_ALL.png", "#",
  "Novelty against colocalisation",
  "Where the prioritised targets sit",
  "Every causal pair positioned by its colocalisation posterior (x) and its plasma immune novelty "
  "score (y), coloured by novelty tier; the dashed line is the PP.H4 ≥ 0.8 threshold. The "
  "high-scoring pairs to the right of that line are the ones the atlas hands over for "
  "experimental work — high novelty on its own is not enough, because a pair with no shared "
  "causal variant may simply reflect two neighbouring signals in linkage disequilibrium."),
]


def build(prs, spec, tag):
    """Figure labels are assigned here rather than stored in the spec: the same spec
    builds both decks and slides get added or removed, so any hard-coded 'Figure 12'
    would go stale the moment the deck changed. A stored label of '#' means 'number me'."""
    n = fignum = 0
    for item in spec:
        n += 1
        if item[0] == "SECTION":
            _, kicker, title, blurb, bullets = item
            section_slide(prs, n, kicker, title, blurb, bullets)
            print(f"  {n:>2}  [section] {title}")
        else:
            sub, fname, label, title, subtitle, cap = item
            fignum += 1
            if label == "#":
                label = f"Figure {fignum}"
            path = F(sub, fname)
            if not os.path.exists(path):
                print(f"  {n:>2}  !! MISSING {sub}/{fname} — slide skipped")
                n -= 1
                fignum -= 1
                continue
            fig_slide(prs, n, tag, label, title, path, cap, subtitle)
            print(f"  {n:>2}  {label:<11} {fname}")
    return n


print("[54] building the main figure deck ...")
prs = new_deck()

# ---- cover
s = blank(prs)
rect(s, 0, 0, SW, SH, ACC)
rect(s, 0, 0, 0.34, SH, ACC2)
txbox(s, 1.15, 1.55, SW - 2.3, 0.4, "PUBLICATION FIGURE DECK", size=13, bold=True,
      color=RGBColor(0xF2, 0xB8, 0xB8))
txbox(s, 1.15, 2.02, SW - 2.3, 1.6,
      "Human Plasma Immune Atlas", size=40, bold=True, color=WHITE)
txbox(s, 1.15, 3.00, SW - 2.6, 0.9,
      "An open, genetics-anchored causal map from the plasma immunome\n"
      "to the human disease phenome", size=16,
      color=RGBColor(0xF0, 0xE0, 0xE2), spacing=1.2)
items = [(f"{N_PROTS}", "causal plasma\nimmune proteins"),
         (f"{N_DIS}", "disease endpoints\nreached"),
         (f"{N_PAIRS:,}", "causal pairs\nFDR < 5 %"),
         (f"{N_COLOC}", "colocalised\nPP.H4 ≥ 0.8"),
         (f"{N_REPL}", "two-population\nreplicated")]
k = len(items); gut = 0.24
w = (SW - 2.3 - gut * (k - 1)) / k
for i, (big, small) in enumerate(items):
    x = 1.15 + i * (w + gut)
    rect(s, x, 4.25, w, 1.15, RGBColor(0x92, 0x1E, 0x33))
    txbox(s, x + 0.08, 4.42, w - 0.16, 0.44, big, size=24, bold=True, color=WHITE,
          align=PP_ALIGN.CENTER)
    txbox(s, x + 0.08, 4.90, w - 0.16, 0.42, small, size=9.5,
          color=RGBColor(0xF0, 0xC8, 0xCC), align=PP_ALIGN.CENTER, spacing=1.05)
txbox(s, 1.15, 5.75, SW - 2.3, 0.35,
      "Live app · https://huggingface.co/spaces/jianlizhao/Human-Plasma-Immune-Atlas",
      size=11.5, color=RGBColor(0xF2, 0xB8, 0xB8))
txbox(s, 1.15, 6.10, SW - 2.3, 0.35,
      "Code · https://github.com/jimmyuab/Human-Plasma-Immune-Atlas-Code",
      size=11.5, color=RGBColor(0xF2, 0xB8, 0xB8))
txbox(s, 1.15, 6.62, SW - 2.3, 0.3,
      "eQTLGen · FinnGen R12 · INTERVAL plasma pQTL · UK Biobank · Human Protein Atlas · MSigDB",
      size=9, color=RGBColor(0xE0, 0xB0, 0xB4))

n = build(prs, MAIN, "figure deck")

# ---- closing methods slide
s = blank(prs)
rect(s, 0, 0, SW, 0.16, ACC)
rect(s, M, BAND_Y + 0.04, 0.075, BAND_H - 0.08, ACC2)
txbox(s, M + 0.20, BAND_Y, SW - 2 * M, 0.40, "Methods and limits", size=19,
      bold=True, anchor=MSO_ANCHOR.MIDDLE)
txbox(s, M + 0.20, BAND_Y + 0.44, SW - 2 * M, 0.38,
      "What the figures do and do not claim", size=11.5, color=GREY,
      anchor=MSO_ANCHOR.MIDDLE)
col_w = (SW - 2 * M - 0.4) / 2
left = ("METHODS\n\n"
        "Instruments — strongest cis-eQTL per plasma immune protein, eQTLGen (n ≈ 31,684).\n\n"
        "Outcomes — FinnGen release R12, every endpoint of the phenome.\n\n"
        "Causal estimation — Wald ratio / Zhu approximation, Benjamini–Hochberg FDR applied "
        "across the whole phenome, not within chapters.\n\n"
        "Colocalisation — coloc.abf with Wakefield approximate Bayes factors; PP.H4 ≥ 0.8 "
        "indicates a shared causal variant.\n\n"
        "Protein level — INTERVAL plasma pQTL (Sun et al. 2018) MR and colocalisation.\n\n"
        "Replication — independent single-cohort UK Biobank GWAS of the matched endpoint.")
right = ("LIMITS\n\n"
         "MR estimates are lifelong genetically-proxied effects. They give a causal direction, "
         "not the effect size of a drug course in an adult patient.\n\n"
         "MHC-region pairs are held at nomination only: long-range LD defeats colocalisation "
         "there, so a shared-variant posterior cannot be trusted.\n\n"
         "cis-eQTL instruments proxy transcript, which is not always circulating protein; the "
         "plasma pQTL layer is the arbiter and its coverage is incomplete.\n\n"
         "Only single-cohort UK Biobank GWAS are used for replication — public meta-analyses of "
         "the same endpoints often include FinnGen, which would be circular.\n\n"
         "Research resource only — not clinical advice, not a validated diagnostic.")
panel_h = FOOT_Y - 0.14 - FIG_Y
for i, (txt, colr) in enumerate([(left, ACC), (right, RGBColor(0x33, 0x33, 0x33))]):
    x = M + i * (col_w + 0.4)
    rect(s, x, FIG_Y, col_w, panel_h, LIGHT)
    rect(s, x, FIG_Y, col_w, 0.055, ACC2)
    txbox(s, x + 0.26, FIG_Y + 0.30, col_w - 0.52, panel_h - 0.6, txt, size=12,
          color=colr, spacing=1.30)
n += 1
footer(s, n, "figure deck")
print(f"  {n:>2}  [methods]")

out = os.path.join(FIG, "Human_Plasma_Immune_Atlas_Figures.pptx")
prs.save(out)
print(f"[54] main deck -> {out}  ({n + 1} slides)")


# ================================================================= CV DECK
print("[54] building the cardiovascular-only deck ...")
CVSPEC = [x for x in MAIN if x[0] in ("cv_novelty", "heart")]
prs2 = new_deck()
s = blank(prs2)
rect(s, 0, 0, SW, SH, ACC)
rect(s, 0, 0, 0.34, SH, ACC2)
txbox(s, 1.15, 1.60, SW - 2.3, 0.4, "NOVELTY ANALYSIS", size=13, bold=True,
      color=RGBColor(0xF2, 0xB8, 0xB8))
txbox(s, 1.15, 2.05, SW - 2.3, 1.5,
      "The Plasma Immunome in\nCardiovascular Disease", size=36, bold=True,
      color=WHITE, spacing=1.05)
txbox(s, 1.15, 3.45, SW - 2.6, 0.8,
      "Which plasma immune proteins cause cardiovascular disease, how much of that\n"
      "signal is genuinely new, and what should be done about it", size=15,
      color=RGBColor(0xF0, 0xE0, 0xE2), spacing=1.2)
items = [(f"{CV_N}", "causal pairs\nFDR < 5 %"),
         (f"{CV_G} × {CV_D}", "proteins ×\nCV endpoints"),
         (f"{CV_COLOC}", "colocalised\nPP.H4 ≥ 0.8"),
         (f"{CV_REPL}", "replicated\nFinland → England"),
         (f"{CV_KNOWN}", "recovered known\ndrug axis")]
k = len(items); gut = 0.24
w = (SW - 2.3 - gut * (k - 1)) / k
for i, (big, small) in enumerate(items):
    x = 1.15 + i * (w + gut)
    rect(s, x, 4.55, w, 1.15, RGBColor(0x92, 0x1E, 0x33))
    txbox(s, x + 0.08, 4.72, w - 0.16, 0.44, big, size=22, bold=True, color=WHITE,
          align=PP_ALIGN.CENTER)
    txbox(s, x + 0.08, 5.20, w - 0.16, 0.42, small, size=9.5,
          color=RGBColor(0xF0, 0xC8, 0xCC), align=PP_ALIGN.CENTER, spacing=1.05)
txbox(s, 1.15, 6.10, SW - 2.3, 0.35,
      "Human Plasma Immune Atlas · layer 7 · FinnGen R12 cardiovascular chapter",
      size=11, color=RGBColor(0xF2, 0xB8, 0xB8))
n2 = build(prs2, CVSPEC, "cardiovascular novelty")
out2 = os.path.join(FIG, "Cardiovascular_Novelty_Figures.pptx")
prs2.save(out2)
print(f"[54] cardiovascular deck -> {out2}  ({n2 + 1} slides)")


# ================================================================= geometry check
print("[54] verifying layout — no zone can overlap:")
print(f"     title band   y = {BAND_Y:.2f} .. {BAND_Y+BAND_H:.2f}")
print(f"     figure box   y = {FIG_Y:.2f} .. {FIG_Y+FIG_H:.2f}   x = {FIG_X:.2f} .. {FIG_X+FIG_W:.2f}")
print(f"     caption band y = {CAP_Y:.2f} .. {CAP_Y+CAP_H:.2f}")
print(f"     footer       y = {FOOT_Y:.2f} .. {FOOT_Y+FOOT_H:.2f}")
assert BAND_Y + BAND_H < FIG_Y and FIG_Y + FIG_H < CAP_Y and CAP_Y + CAP_H < FOOT_Y <= SH
print("[54] OK — bands are disjoint and inside the slide")
